### ISSUE TITLE
webpack 4.x 自带压缩js功能

### ISSUE THREAD

**Issue by confuseMyself** [LiHongyao/Blogs#2]
webpack4.x 废弃了uglifyjs-webpack-plugin，并且自带js代码压缩功能，
在optimization配置minimize:true 即可压缩js代码。

**Comment by lihongyao** [comment]
收到 谢谢提示


| |
李鸿耀
|
|
邮箱：lihy_online@163.com
|

签名由 网易邮箱大师 定制

在2019年11月30日 10:03，嗨！三千 写道：

webpack4.x 废弃了uglifyjs-webpack-plugin，并且自带js代码压缩功能，
在optimization配置minimize:true 即可压缩js代码。
